"""add_foreign_key_created_by_to_layovers

Revision ID: 72fdc482e086
Revises: 9e7d3ccd1043
Create Date: 2025-11-01 22:23:02.079270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '72fdc482e086'
down_revision: Union[str, Sequence[str], None] = '9e7d3ccd1043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('layovers', 'cancelled_at',
               existing_type=mysql.DATETIME(),
               comment='When cancellation recorded',
               existing_nullable=True)
    op.alter_column('layovers', 'cancellation_reason',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Reason for cancellation',
               existing_nullable=True)
    op.alter_column('layovers', 'cancellation_notice_hours',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Hours between cancel time and check-in',
               existing_nullable=True)
    op.alter_column('layovers', 'cancellation_charge_applies',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Whether any cancellation charge applies',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('layovers', 'cancellation_charge_policy',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment="Tier label (e.g., 'no_charge', '24_48h_50', 'lt_24h_100')",
               existing_nullable=True)
    op.alter_column('layovers', 'cancellation_charge_percent',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Percent of charge applied (e.g., 50, 100)',
               existing_nullable=True)
    op.alter_column('layovers', 'cancellation_fee_cents',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Computed fee (if available) in cents',
               existing_nullable=True)
    op.create_foreign_key(None, 'layovers', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'layovers', type_='foreignkey')
    op.alter_column('layovers', 'cancellation_fee_cents',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='Computed fee (if available) in cents',
               existing_nullable=True)
    op.alter_column('layovers', 'cancellation_charge_percent',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='Percent of charge applied (e.g., 50, 100)',
               existing_nullable=True)
    op.alter_column('layovers', 'cancellation_charge_policy',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment="Tier label (e.g., 'no_charge', '24_48h_50', 'lt_24h_100')",
               existing_nullable=True)
    op.alter_column('layovers', 'cancellation_charge_applies',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Whether any cancellation charge applies',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('layovers', 'cancellation_notice_hours',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='Hours between cancel time and check-in',
               existing_nullable=True)
    op.alter_column('layovers', 'cancellation_reason',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Reason for cancellation',
               existing_nullable=True)
    op.alter_column('layovers', 'cancelled_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='When cancellation recorded',
               existing_nullable=True)
    # ### end Alembic commands ###
