"""Initial schema - all tables (final fix)

Revision ID: f6203542bbfc
Revises: 
Create Date: 2025-10-29 18:42:00.017544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f6203542bbfc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Audit log ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='User ID (NULL = system action)'),
    sa.Column('user_role', sa.String(length=50), nullable=True, comment='User role at time of action'),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Action timestamp'),
    sa.Column('action_type', sa.String(length=100), nullable=False, comment='Action type: created, updated, status_changed, confirmed, etc.'),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='Entity type: layover, user, hotel, note, etc.'),
    sa.Column('entity_id', sa.Integer(), nullable=False, comment='Entity ID'),
    sa.Column('details', mysql.JSON(), nullable=True, comment='Details JSON: {"before": {...}, "after": {...}, "note": "..."}'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IPv4 or IPv6 address'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='Browser user agent'),
    sa.Column('log_date', sa.Date(), nullable=False, comment='Date for partition pruning'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action_type'], unique=False)
    op.create_index('idx_audit_date', 'audit_logs', ['log_date'], unique=False)
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_entity_time', 'audit_logs', ['entity_type', 'entity_id', 'timestamp'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_log_date'), 'audit_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Hotel ID'),
    sa.Column('station_id', sa.Integer(), nullable=False, comment='Station where hotel is located'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Hotel name'),
    sa.Column('address', sa.Text(), nullable=False, comment='Full hotel address'),
    sa.Column('city', sa.String(length=100), nullable=False, comment='City name'),
    sa.Column('postal_code', sa.String(length=20), nullable=True, comment='Postal/ZIP code'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Primary phone number'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Primary contact email'),
    sa.Column('secondary_emails', mysql.JSON(), nullable=True, comment='Array of additional emails for CC'),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True, comment='WhatsApp number (if different from phone)'),
    sa.Column('whatsapp_enabled', sa.Boolean(), server_default='0', nullable=False, comment='Enable WhatsApp notifications'),
    sa.Column('contract_type', sa.String(length=50), nullable=True, comment='Contract type: ad_hoc, block_booking, preferred_rate'),
    sa.Column('contract_rate', sa.Integer(), nullable=True, comment='Pre-negotiated rate per room per night (in cents)'),
    sa.Column('contract_valid_until', sa.String(length=10), nullable=True, comment='Contract expiry date'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Internal notes about hotel (e.g., preferences, issues)'),
    sa.Column('performance_metrics', mysql.JSON(), nullable=True, comment='Cached performance statistics'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='Hotel active status'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID of creator'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_hotel_active', 'hotels', ['is_active'], unique=False)
    op.create_index('idx_hotel_email', 'hotels', ['email'], unique=False)
    op.create_index('idx_hotel_station', 'hotels', ['station_id'], unique=False)
    op.create_index('idx_hotel_station_active', 'hotels', ['station_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_hotels_email'), 'hotels', ['email'], unique=False)
    op.create_index(op.f('ix_hotels_is_active'), 'hotels', ['is_active'], unique=False)
    op.create_index(op.f('ix_hotels_station_id'), 'hotels', ['station_id'], unique=False)
    op.create_table('layovers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Layover ID (internal)'),
    sa.Column('uuid', sa.String(length=36), nullable=False, comment='UUID for external references (URLs, exports)'),
    sa.Column('origin_station_code', sa.String(length=10), nullable=True, comment='Departure airport code'),
    sa.Column('destination_station_code', sa.String(length=10), nullable=True, comment='Arrival airport code'),
    sa.Column('station_id', sa.Integer(), nullable=False, comment='Station handling this layover'),
    sa.Column('hotel_id', sa.Integer(), nullable=True, comment='Assigned hotel'),
    sa.Column('layover_reason', sa.Enum('SCHEDULED_REST', 'POSITIONING', 'TRAINING', 'STANDBY', 'IRREGULAR_OPS', 'OTHER', name='layoverreason'), server_default='scheduled_rest', nullable=False, comment='Reason for layover'),
    sa.Column('operational_flight_number', sa.String(length=20), nullable=True, comment='Flight number if operational (e.g., QS100)'),
    sa.Column('positioning_flight_number', sa.String(length=20), nullable=True, comment='Flight number if positioning/deadheading (e.g., BA112)'),
    sa.Column('trip_id', sa.String(length=50), nullable=True, comment='Groups related layovers (e.g., QS-JAN25-P001)'),
    sa.Column('trip_sequence', sa.Integer(), nullable=True, comment='Order in trip: 1, 2, 3...'),
    sa.Column('is_positioning', sa.Boolean(), server_default='0', nullable=False, comment='True if crew deadheading'),
    sa.Column('check_in_date', sa.Date(), nullable=False, comment='Check-in date'),
    sa.Column('check_in_time', sa.Time(), nullable=False, comment='Check-in time'),
    sa.Column('check_out_date', sa.Date(), nullable=False, comment='Check-out date'),
    sa.Column('check_out_time', sa.Time(), nullable=False, comment='Check-out time'),
    sa.Column('crew_count', sa.Integer(), nullable=False, comment='Total number of crew members'),
    sa.Column('room_breakdown', mysql.JSON(), nullable=True, comment='Room breakdown JSON: {"singles": 3, "doubles": 1, "suites": 0}'),
    sa.Column('special_requirements', sa.Text(), nullable=True, comment='Special requirements or notes'),
    sa.Column('transport_required', sa.Boolean(), server_default='0', nullable=False, comment='Transport required flag'),
    sa.Column('transport_details', sa.Text(), nullable=True, comment='Transport details if required'),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PENDING', 'CONFIRMED', 'DECLINED', 'CHANGES_REQUESTED', 'ON_HOLD', 'AMENDED', 'ESCALATED', 'COMPLETED', 'CANCELLED', name='layoverstatus'), server_default='DRAFT', nullable=False, comment='Current workflow status'),
    sa.Column('sent_at', sa.DateTime(), nullable=True, comment='When sent to hotel'),
    sa.Column('pending_at', sa.DateTime(), nullable=True, comment='When marked pending'),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True, comment='When hotel confirmed'),
    sa.Column('declined_at', sa.DateTime(), nullable=True, comment='When hotel declined'),
    sa.Column('escalated_at', sa.DateTime(), nullable=True, comment='When escalated'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='When completed'),
    sa.Column('on_hold_at', sa.DateTime(), nullable=True, comment='When put on hold'),
    sa.Column('on_hold_reason', sa.String(length=255), nullable=True, comment='Reason for hold'),
    sa.Column('on_hold_by', sa.Integer(), nullable=True, comment='User ID who put on hold'),
    sa.Column('amendment_count', sa.Integer(), server_default='0', nullable=False, comment='Number of amendments after confirmation'),
    sa.Column('last_amended_at', sa.DateTime(), nullable=True, comment='Last amendment timestamp'),
    sa.Column('amendment_reason', sa.Text(), nullable=True, comment='Reason for amendment'),
    sa.Column('hotel_notified_of_amendment', sa.Boolean(), server_default='0', nullable=False, comment='Hotel notified of changes flag'),
    sa.Column('hotel_response_note', sa.Text(), nullable=True, comment='Note from hotel (decline reason, change request)'),
    sa.Column('hotel_response_metadata', mysql.JSON(), nullable=True, comment='IP, user-agent, timestamp from confirmation link'),
    sa.Column('last_reminder_sent_at', sa.DateTime(), nullable=True, comment='Last reminder timestamp'),
    sa.Column('reminder_count', sa.Integer(), server_default='0', nullable=False, comment='Number of reminders sent'),
    sa.Column('reminders_paused', sa.Boolean(), server_default='0', nullable=False, comment='Reminders paused flag'),
    sa.Column('reminders_paused_reason', sa.String(length=255), nullable=True, comment='Reason for pausing reminders'),
    sa.Column('reminders_paused_at', sa.DateTime(), nullable=True, comment='When reminders paused'),
    sa.Column('reminders_paused_by', sa.Integer(), nullable=True, comment='User ID who paused reminders'),
    sa.Column('hotel_confirmation_number', sa.String(length=100), nullable=True, comment='Hotel confirmation number'),
    sa.Column('estimated_cost', sa.Integer(), nullable=True, comment='Estimated cost in cents'),
    sa.Column('actual_cost', sa.Integer(), nullable=True, comment='Actual cost in cents'),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False, comment='Currency code (ISO 4217)'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='User ID of creator'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint("(layover_reason != 'scheduled_rest') OR (origin_station_code IS NOT NULL AND destination_station_code IS NOT NULL)", name='chk_route_required_for_scheduled'),
    sa.CheckConstraint('crew_count > 0 AND crew_count <= 100', name='chk_crew_count'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_layover_check_in', 'layovers', ['check_in_date'], unique=False)
    op.create_index('idx_layover_created_by', 'layovers', ['created_by'], unique=False)
    op.create_index('idx_layover_hotel', 'layovers', ['hotel_id'], unique=False)
    op.create_index('idx_layover_reason', 'layovers', ['layover_reason'], unique=False)
    op.create_index('idx_layover_station', 'layovers', ['station_id'], unique=False)
    op.create_index('idx_layover_station_status', 'layovers', ['station_id', 'status'], unique=False)
    op.create_index('idx_layover_status', 'layovers', ['status'], unique=False)
    op.create_index('idx_layover_status_sent', 'layovers', ['status', 'sent_at'], unique=False)
    op.create_index('idx_layover_trip', 'layovers', ['trip_id', 'trip_sequence'], unique=False)
    op.create_index('idx_layover_uuid', 'layovers', ['uuid'], unique=False)
    op.create_index(op.f('ix_layovers_check_in_date'), 'layovers', ['check_in_date'], unique=False)
    op.create_index(op.f('ix_layovers_created_by'), 'layovers', ['created_by'], unique=False)
    op.create_index(op.f('ix_layovers_hotel_id'), 'layovers', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_layovers_layover_reason'), 'layovers', ['layover_reason'], unique=False)
    op.create_index(op.f('ix_layovers_station_id'), 'layovers', ['station_id'], unique=False)
    op.create_index(op.f('ix_layovers_status'), 'layovers', ['status'], unique=False)
    op.create_index(op.f('ix_layovers_trip_id'), 'layovers', ['trip_id'], unique=False)
    op.create_index(op.f('ix_layovers_uuid'), 'layovers', ['uuid'], unique=True)
    op.create_table('confirmation_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Token ID'),
    sa.Column('token', sa.String(length=36), nullable=False, comment='UUID token for URL'),
    sa.Column('token_type', sa.Enum('HOTEL_CONFIRMATION', 'CREW_PORTAL', 'PASSWORD_RESET', name='tokentype'), nullable=False, comment='Token type'),
    sa.Column('layover_id', sa.Integer(), nullable=False, comment='Associated layover'),
    sa.Column('hotel_id', sa.Integer(), nullable=True, comment='For hotel_confirmation type'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='For crew_portal or password_reset type'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='Token expiry timestamp'),
    sa.Column('used_at', sa.DateTime(), nullable=True, comment='When token was used'),
    sa.Column('is_valid', sa.Boolean(), server_default='1', nullable=False, comment='Token validity flag'),
    sa.Column('response_metadata', mysql.JSON(), nullable=True, comment='Metadata JSON: {"ip": "...", "user_agent": "...", "action": "..."}'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['layover_id'], ['layovers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_token', 'confirmation_tokens', ['token'], unique=False)
    op.create_index('idx_token_expires', 'confirmation_tokens', ['expires_at'], unique=False)
    op.create_index('idx_token_layover', 'confirmation_tokens', ['layover_id'], unique=False)
    op.create_index('idx_token_valid', 'confirmation_tokens', ['is_valid'], unique=False)
    op.create_index('idx_token_validation', 'confirmation_tokens', ['token', 'is_valid', 'expires_at'], unique=False)
    op.create_index(op.f('ix_confirmation_tokens_expires_at'), 'confirmation_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_confirmation_tokens_is_valid'), 'confirmation_tokens', ['is_valid'], unique=False)
    op.create_index(op.f('ix_confirmation_tokens_layover_id'), 'confirmation_tokens', ['layover_id'], unique=False)
    op.create_index(op.f('ix_confirmation_tokens_token'), 'confirmation_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_confirmation_tokens_token_type'), 'confirmation_tokens', ['token_type'], unique=False)
    op.create_table('file_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='File ID'),
    sa.Column('layover_id', sa.Integer(), nullable=False, comment='Associated layover'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='Original file name'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='File size in bytes'),
    sa.Column('file_type', sa.String(length=100), nullable=False, comment='MIME type'),
    sa.Column('storage_key', sa.String(length=500), nullable=False, comment='S3/MinIO object key or file path'),
    sa.Column('scan_status', sa.Enum('PENDING', 'CLEAN', 'INFECTED', 'FAILED', name='scanstatus'), server_default='pending', nullable=False, comment='Virus scan status'),
    sa.Column('scanned_at', sa.DateTime(), nullable=True, comment='When file was scanned'),
    sa.Column('uploaded_by', sa.Integer(), nullable=False, comment='User ID of uploader'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('is_deleted', sa.Integer(), server_default='0', nullable=False, comment='Soft delete flag: 0=active, 1=deleted'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp'),
    sa.Column('deleted_by', sa.Integer(), nullable=True, comment='User ID who deleted this record'),
    sa.ForeignKeyConstraint(['layover_id'], ['layovers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_file_deleted', 'file_attachments', ['is_deleted'], unique=False)
    op.create_index('idx_file_layover', 'file_attachments', ['layover_id'], unique=False)
    op.create_index('idx_file_scan', 'file_attachments', ['scan_status'], unique=False)
    op.create_index('idx_file_uploaded_by', 'file_attachments', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_file_attachments_layover_id'), 'file_attachments', ['layover_id'], unique=False)
    op.create_index(op.f('ix_file_attachments_scan_status'), 'file_attachments', ['scan_status'], unique=False)
    op.create_index(op.f('ix_file_attachments_uploaded_by'), 'file_attachments', ['uploaded_by'], unique=False)
    op.create_table('layover_crew',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Assignment ID'),
    sa.Column('layover_id', sa.Integer(), nullable=False, comment='Layover ID'),
    sa.Column('crew_member_id', sa.Integer(), nullable=False, comment='Crew member ID'),
    sa.Column('room_number', sa.String(length=20), nullable=True, comment='Hotel room number'),
    sa.Column('room_type', sa.String(length=50), nullable=True, comment='Room type: single, double, suite'),
    sa.Column('room_allocation_priority', sa.Integer(), nullable=True, comment='Priority for room allocation (based on rank)'),
    sa.Column('is_primary_contact', sa.Boolean(), server_default='0', nullable=False, comment='Primary contact for this layover (Captain/Purser)'),
    sa.Column('notified_at', sa.DateTime(), nullable=True, comment='When crew member was notified'),
    sa.Column('notification_status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notificationstatus'), server_default='pending', nullable=False, comment='Notification delivery status'),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True, comment='When crew acknowledged receipt'),
    sa.Column('acknowledgment_ip', sa.String(length=45), nullable=True, comment='IP address of acknowledgment'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['crew_member_id'], ['crew_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['layover_id'], ['layovers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('layover_id', 'crew_member_id', name='uq_layover_crew'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_layover_crew_layover', 'layover_crew', ['layover_id'], unique=False)
    op.create_index('idx_layover_crew_member', 'layover_crew', ['crew_member_id'], unique=False)
    op.create_index('idx_layover_crew_primary', 'layover_crew', ['layover_id', 'is_primary_contact'], unique=False)
    op.create_index(op.f('ix_layover_crew_crew_member_id'), 'layover_crew', ['crew_member_id'], unique=False)
    op.create_index(op.f('ix_layover_crew_layover_id'), 'layover_crew', ['layover_id'], unique=False)
    op.create_table('layover_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Note ID'),
    sa.Column('layover_id', sa.Integer(), nullable=False, comment='Associated layover'),
    sa.Column('note_text', sa.Text(), nullable=False, comment='Note content'),
    sa.Column('tagged_user_ids', mysql.JSON(), nullable=True, comment='Array of user IDs mentioned in note'),
    sa.Column('is_internal', sa.Boolean(), server_default='1', nullable=False, comment='True = internal only, False = visible to hotel'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='User ID of note author'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['layover_id'], ['layovers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_note_created_at', 'layover_notes', ['created_at'], unique=False)
    op.create_index('idx_note_created_by', 'layover_notes', ['created_by'], unique=False)
    op.create_index('idx_note_layover', 'layover_notes', ['layover_id'], unique=False)
    op.create_index(op.f('ix_layover_notes_created_by'), 'layover_notes', ['created_by'], unique=False)
    op.create_index(op.f('ix_layover_notes_layover_id'), 'layover_notes', ['layover_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Notification ID'),
    sa.Column('layover_id', sa.Integer(), nullable=True, comment='Associated layover (if applicable)'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Recipient user (if internal)'),
    sa.Column('notification_type', sa.Enum('HOTEL_REQUEST', 'HOTEL_REMINDER', 'OPS_CONFIRMATION', 'OPS_DECLINE', 'OPS_ESCALATION', 'CREW_NOTIFICATION', 'AMENDMENT_NOTIFICATION', 'PASSWORD_RESET', name='notificationtype'), nullable=False, comment='Notification type'),
    sa.Column('recipient_email', sa.String(length=255), nullable=True, comment='Recipient email address'),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True, comment='Recipient phone number'),
    sa.Column('channel', sa.Enum('EMAIL', 'WHATSAPP', 'SMS', 'IN_APP', name='notificationchannel'), nullable=False, comment='Delivery channel'),
    sa.Column('subject', sa.String(length=500), nullable=True, comment='Email subject line'),
    sa.Column('body_text', sa.Text(), nullable=True, comment='Plain text body'),
    sa.Column('body_html', sa.Text(), nullable=True, comment='HTML body'),
    sa.Column('template_name', sa.String(length=100), nullable=True, comment='Template used for rendering'),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'BOUNCED', name='notificationstatus'), server_default='pending', nullable=False, comment='Delivery status'),
    sa.Column('sent_at', sa.DateTime(), nullable=True, comment='When sent'),
    sa.Column('delivered_at', sa.DateTime(), nullable=True, comment='When delivered (if confirmed)'),
    sa.Column('failed_at', sa.DateTime(), nullable=True, comment='When failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if failed'),
    sa.Column('external_id', sa.String(length=255), nullable=True, comment='External service message ID (SendGrid, Twilio, etc.)'),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False, comment='Number of retry attempts'),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True, comment='Next retry timestamp'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['layover_id'], ['layovers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_notif_layover', 'notifications', ['layover_id'], unique=False)
    op.create_index('idx_notif_retry', 'notifications', ['next_retry_at', 'status'], unique=False)
    op.create_index('idx_notif_sent', 'notifications', ['sent_at'], unique=False)
    op.create_index('idx_notif_status', 'notifications', ['status'], unique=False)
    op.create_index('idx_notif_type', 'notifications', ['notification_type'], unique=False)
    op.create_index('idx_notif_user', 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_channel'), 'notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_notifications_layover_id'), 'notifications', ['layover_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_sent_at'), 'notifications', ['sent_at'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_sent_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_layover_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_channel'), table_name='notifications')
    op.drop_index('idx_notif_user', table_name='notifications')
    op.drop_index('idx_notif_type', table_name='notifications')
    op.drop_index('idx_notif_status', table_name='notifications')
    op.drop_index('idx_notif_sent', table_name='notifications')
    op.drop_index('idx_notif_retry', table_name='notifications')
    op.drop_index('idx_notif_layover', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_layover_notes_layover_id'), table_name='layover_notes')
    op.drop_index(op.f('ix_layover_notes_created_by'), table_name='layover_notes')
    op.drop_index('idx_note_layover', table_name='layover_notes')
    op.drop_index('idx_note_created_by', table_name='layover_notes')
    op.drop_index('idx_note_created_at', table_name='layover_notes')
    op.drop_table('layover_notes')
    op.drop_index(op.f('ix_layover_crew_layover_id'), table_name='layover_crew')
    op.drop_index(op.f('ix_layover_crew_crew_member_id'), table_name='layover_crew')
    op.drop_index('idx_layover_crew_primary', table_name='layover_crew')
    op.drop_index('idx_layover_crew_member', table_name='layover_crew')
    op.drop_index('idx_layover_crew_layover', table_name='layover_crew')
    op.drop_table('layover_crew')
    op.drop_index(op.f('ix_file_attachments_uploaded_by'), table_name='file_attachments')
    op.drop_index(op.f('ix_file_attachments_scan_status'), table_name='file_attachments')
    op.drop_index(op.f('ix_file_attachments_layover_id'), table_name='file_attachments')
    op.drop_index('idx_file_uploaded_by', table_name='file_attachments')
    op.drop_index('idx_file_scan', table_name='file_attachments')
    op.drop_index('idx_file_layover', table_name='file_attachments')
    op.drop_index('idx_file_deleted', table_name='file_attachments')
    op.drop_table('file_attachments')
    op.drop_index(op.f('ix_confirmation_tokens_token_type'), table_name='confirmation_tokens')
    op.drop_index(op.f('ix_confirmation_tokens_token'), table_name='confirmation_tokens')
    op.drop_index(op.f('ix_confirmation_tokens_layover_id'), table_name='confirmation_tokens')
    op.drop_index(op.f('ix_confirmation_tokens_is_valid'), table_name='confirmation_tokens')
    op.drop_index(op.f('ix_confirmation_tokens_expires_at'), table_name='confirmation_tokens')
    op.drop_index('idx_token_validation', table_name='confirmation_tokens')
    op.drop_index('idx_token_valid', table_name='confirmation_tokens')
    op.drop_index('idx_token_layover', table_name='confirmation_tokens')
    op.drop_index('idx_token_expires', table_name='confirmation_tokens')
    op.drop_index('idx_token', table_name='confirmation_tokens')
    op.drop_table('confirmation_tokens')
    op.drop_index(op.f('ix_layovers_uuid'), table_name='layovers')
    op.drop_index(op.f('ix_layovers_trip_id'), table_name='layovers')
    op.drop_index(op.f('ix_layovers_status'), table_name='layovers')
    op.drop_index(op.f('ix_layovers_station_id'), table_name='layovers')
    op.drop_index(op.f('ix_layovers_layover_reason'), table_name='layovers')
    op.drop_index(op.f('ix_layovers_hotel_id'), table_name='layovers')
    op.drop_index(op.f('ix_layovers_created_by'), table_name='layovers')
    op.drop_index(op.f('ix_layovers_check_in_date'), table_name='layovers')
    op.drop_index('idx_layover_uuid', table_name='layovers')
    op.drop_index('idx_layover_trip', table_name='layovers')
    op.drop_index('idx_layover_status_sent', table_name='layovers')
    op.drop_index('idx_layover_status', table_name='layovers')
    op.drop_index('idx_layover_station_status', table_name='layovers')
    op.drop_index('idx_layover_station', table_name='layovers')
    op.drop_index('idx_layover_reason', table_name='layovers')
    op.drop_index('idx_layover_hotel', table_name='layovers')
    op.drop_index('idx_layover_created_by', table_name='layovers')
    op.drop_index('idx_layover_check_in', table_name='layovers')
    op.drop_table('layovers')
    op.drop_index(op.f('ix_hotels_station_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_is_active'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_email'), table_name='hotels')
    op.drop_index('idx_hotel_station_active', table_name='hotels')
    op.drop_index('idx_hotel_station', table_name='hotels')
    op.drop_index('idx_hotel_email', table_name='hotels')
    op.drop_index('idx_hotel_active', table_name='hotels')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_log_date'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_entity_time', table_name='audit_logs')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_index('idx_audit_date', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
